language java
script :
  - mvn clean verify
jobs:
  include:
    - stage: build docker image
      script:
      - docker login -u "$DOCKER_USERNAME" --password "$DOCKER_HUB_PWD"
      - docker build -t sample-application-students .
      - docker tag sample-application-students $DOCKER_USERNAME/sample-application-students
      - docker push $DOCKER_USERNAME/sample-application-students