language : java

jobs:
  include:
    - stage: Build
      script :
        - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=tcrepaldi_sample-application-students

    - stage: build docker image
      script:
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_HUB_PWD"
        - docker build -t sample-application-students-db ./sample-application-db-changelog-job
        - docker tag sample-application-students-db $DOCKER_USERNAME/sample-application-students-db
        - docker push $DOCKER_USERNAME/sample-application-students-db
    - script:
      - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_HUB_PWD"
      - docker build -t sample-application-students-http ./sample-application-http-api-server
      - docker tag sample-application-students-http $DOCKER_USERNAME/sample-application-students-http
      - docker push $DOCKER_USERNAME/sample-application-students-http

addons:
  sonarcloud:
    organization: "tcrepaldi"
    token:
      secure: "$SONARCLOUD" # encrypted value of your token